spring:
  application:
    name: change-service

  datasource:
    url: jdbc:h2:mem:change_service
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

change:
  service:
    supported:
      bills: 1.0, 2.0, 5.0, 10.0, 20.0, 50.0, 100.0
    initial-coins:
      0.25: 100
      0.10: 100
      0.05: 100
      0.01: 100